silverstrike/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView


from silverstrike import api
from silverstrike.views import account as account_views
from silverstrike.views import categories as category_views
from silverstrike.views import charts as chart_views
from silverstrike.views import imports as import_views
from silverstrike.views import index as general_views
from silverstrike.views import recurrences as recurrence_views
from silverstrike.views import transactions as transaction_views


urlpatterns = [
    url(r'^$', general_views.IndexView.as_view(), name='index'),
    url(r'^auth/', include('allauth.urls')),

    url(r'^transactions/$', transaction_views.TransactionIndex.as_view(), name='transactions'),
    url(r'^transactions/(?P<pk>\d+)/$',
        transaction_views.TransactionDetailView.as_view(), name='transaction_detail'),
    url(r'^transactions/(?P<pk>\d+)/update/$',
        transaction_views.TransactionUpdateView.as_view(), name='transaction_update'),
    url(r'^transactions/(?P<pk>\d+)/split/$',
        transaction_views.SplitUpdate.as_view(), name='split_update'),
    url(r'^transactions/(?P<pk>\d+)/delete/$',
        transaction_views.TransactionDeleteView.as_view(), name='transaction_delete'),
    url(r'^transactions/create/transfer/$',
        transaction_views.TransferCreate.as_view(), name='transfer_new'),
    url(r'^transactions/create/withdraw/$',
        transaction_views.WithdrawCreate.as_view(), name='withdraw_new'),
    url(r'^transactions/create/deposit/$',
        transaction_views.DepositCreate.as_view(), name='deposit_new'),
    url(r'^transactions/create/split/$',
        transaction_views.SplitCreate.as_view(), name='split_create'),

    url(r'^accounts/(?P<pk>\d+)/update/$',
        account_views.AccountUpdate.as_view(), name='account_update'),
    url(r'^accounts/(?P<pk>\d+)/delete/$',
        account_views.AccountDelete.as_view(), name='account_delete'),
    url(r'^accounts/(?P<pk>\d+)/(?P<month>\S+)/$',
        account_views.AccountView.as_view(), name='account_detail'),
    url(r'^accounts/(?P<pk>\d+)/$', account_views.AccountView.as_view(), name='account_view'),
    url(r'^accounts/(?P<pk>\d+)/reconcile$',
        account_views.ReconcileView.as_view(), name='account_reconcile'),

    url(r'^accounts/new$', account_views.AccountCreate.as_view(), name='account_new'),

    url(r'^accounts$',
        account_views.AccountIndex.as_view(), name='accounts'),

    url(r'^recurrences/$',
        recurrence_views.RecurringTransactionIndex.as_view(), name='recurrences'),
    url(r'^recurrences/create$',
        recurrence_views.RecurrenceCreateView.as_view(), name='recurrence_create'),
    url(r'^recurrences/(?P<pk>\d+)/$', recurrence_views.RecurrenceDetailView.as_view(),
        name='recurrence_detail'),
    url(r'^recurrences/(?P<pk>\d+)/update$', recurrence_views.RecurrenceUpdateView.as_view(),
        name='recurrence_update'),
    url(r'^recurrences/(?P<pk>\d+)/delete$', recurrence_views.RecurrenceDeleteView.as_view(),
        name='recurrence_delete'),
    url(r'^recurrences/(?P<pk>\d+)/transaction/create$',
        recurrence_views.RecurrenceTransactionCreateView.as_view(),
        name='recurrence_transaction_create'),


    url(r'^categories/$', category_views.CategoryIndex.as_view(), name='categories'),
    url(r'^categories/create/$',
        category_views.CategoryCreateView.as_view(), name='category_create'),
    url(r'^categories/(?P<pk>\d+)/$',
        category_views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^categories/(?P<pk>\d+)/(?P<month>\S+)/$',
        category_views.CategoryDetailView.as_view(), name='category_month'),
    url(r'^categories/(?P<pk>\d+)/delete$', category_views.CategoryDeleteView.as_view(),
        name='category_delete'),
    url(r'^categories/(?P<pk>\d+)/update$', category_views.CategoryUpdateView.as_view(),
        name='category_update'),

    url(r'^charts$', chart_views.ChartView.as_view(), name='charts'),

    url(r'^api/accounts/(?P<account_type>\w+)$', api.get_accounts, name='api_accounts'),
    url(r'^api/balance/(?P<dstart>\S+)/(?P<dend>\S+)/$',
        api.get_balances, name='api_balance'),
    url(r'^api/accounts_balance/(?P<dstart>\S+)/(?P<dend>\S+)/$',
        api.get_accounts_balance, name='api_accounts_balance'),

    url(r'^manifest.json$', TemplateView.as_view(template_name='silverstrike/manifest.json'),
        name='manifest'),

    url(r'^import/$', import_views.ImportView.as_view(), name='import'),
    url(r'^import/firefly/$', import_views.ImportFireflyView.as_view(), name='import_firefly'),
    url(r'^import/generic$', import_views.ImportUploadView.as_view(), name='import_generic'),
    url(r'^import/generic/(?P<uuid>[0-9a-f-]+)/$', import_views.ImportConfigureView.as_view(),
        name='import_configure'),
    url(r'^import/generic/(?P<uuid>[0-9a-f-]+)/process/(?P<config_pk>\d+)/$',
        import_views.ImportProcessView.as_view(), name='import_process'),

    url(r'^export/$', import_views.ExportView.as_view(), name='export'),
]

silverstrike/forms.py
from datetime import date
from itertools import groupby

from django import forms
from django.forms.models import ModelChoiceField, ModelChoiceIterator, ModelMultipleChoiceField
from django.utils.translation import ugettext as _

from .models import (Account, Category, ImportConfiguration, ImportFile,
                     RecurringTransaction, Split, Transaction)


class ImportUploadForm(forms.ModelForm):
    class Meta:
        model = ImportFile
        fields = ['file']
    configuration = forms.ModelChoiceField(queryset=ImportConfiguration.objects.all(),
                                           required=False)


class AccountCreateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'initial_balance', 'active', 'show_on_dashboard']

    initial_balance = forms.DecimalField(max_digits=10, decimal_places=2, initial=0)

    def save(self, commit=True):
        account = super(AccountCreateForm, self).save(commit)
        if self.cleaned_data['initial_balance']:
            account.set_initial_balance(self.cleaned_data['initial_balance'])
        return account


class CSVDefinitionForm(forms.Form):
    field_type = forms.ChoiceField(choices=ImportConfiguration.FIELD_TYPES)


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['title', 'source_account', 'destination_account',
                  'amount', 'date', 'value_date', 'category', 'notes']

    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0.01)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)
    value_date = forms.DateField(required=False)

    source_account = forms.ModelChoiceField(queryset=Account.objects.filter(
        account_type=Account.PERSONAL, active=True))
    destination_account = forms.ModelChoiceField(queryset=Account.objects.filter(
        account_type=Account.PERSONAL, active=True))

    def save(self, commit=True):
        transaction = super().save(commit)
        src = self.cleaned_data['source_account']
        dst = self.cleaned_data['destination_account']
        amount = self.cleaned_data['amount']
        value_date = self.cleaned_data.get('value_date') or transaction.date
        Split.objects.update_or_create(transaction=transaction, amount__lt=0,
                                       defaults={'amount': -amount, 'account': src,
                                                 'opposing_account': dst, 'date': value_date,
                                                 'title': transaction.title,
                                                 'category': self.cleaned_data['category']})
        Split.objects.update_or_create(transaction=transaction, amount__gt=0,
                                       defaults={'amount': amount, 'account': dst,
                                                 'opposing_account': src, 'date': value_date,
                                                 'title': transaction.title,
                                                 'category': self.cleaned_data['category']})
        return transaction


class TransferForm(TransactionForm):
    def save(self, commit=True):
        transaction = super().save(commit)
        src = self.cleaned_data['source_account']
        dst = self.cleaned_data['destination_account']
        amount = self.cleaned_data['amount']
        Split.objects.update_or_create(transaction=transaction, amount__lt=0,
                                       defaults={'amount': -amount, 'account': src,
                                                 'opposing_account': dst, 'date': transaction.date,
                                                 'title': transaction.title,
                                                 'category': self.cleaned_data['category']})
        Split.objects.update_or_create(transaction=transaction, amount__gt=0,
                                       defaults={'amount': amount, 'account': dst,
                                                 'opposing_account': src, 'date': transaction.date,
                                                 'title': transaction.title,
                                                 'category': self.cleaned_data['category']})
        return transaction

    def clean(self):
        super().clean()
        self.instance.transaction_type = Transaction.TRANSFER
        if self.cleaned_data['source_account'] == self.cleaned_data['destination_account']:
            error = 'source and destination account have to be different'
            self.add_error('destination_account', error)
            self.add_error('source_account', error)


class WithdrawForm(TransactionForm):
    destination_account = forms.CharField(max_length=64, label=_('Debitor'),
                                          widget=forms.TextInput(attrs={'autocomplete': 'off'}))

    def save(self, commit=True):
        account, _ = Account.objects.get_or_create(name=self.cleaned_data['destination_account'],
                                                   account_type=Account.EXPENSE)
        self.cleaned_data['destination_account'] = account
        return super().save(commit)

    def clean(self):
        super().clean()
        self.instance.transaction_type = Transaction.WITHDRAW


class DepositForm(TransactionForm):
    source_account = forms.CharField(max_length=64, label=_('Creditor'),
                                     widget=forms.TextInput(attrs={'autocomplete': 'off'}))

    def save(self, commit=True):
        account, _ = Account.objects.get_or_create(name=self.cleaned_data['source_account'],
                                                   account_type=Account.REVENUE)
        self.cleaned_data['source_account'] = account
        return super().save(commit)

    def clean(self):
        super().clean()
        self.instance.transaction_type = Transaction.DEPOSIT


class RecurringTransactionForm(forms.ModelForm):
    class Meta:
        model = RecurringTransaction
        fields = ['title', 'transaction_type', 'date', 'amount',
                  'src', 'dst', 'category', 'recurrence']

    src = forms.CharField(max_length=64, label=_('Source Account'),
                          widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    dst = forms.CharField(max_length=64, label=_('Destination Account'),
                          widget=forms.TextInput(attrs={'autocomplete': 'off'}))

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount < 0:
            raise forms.ValidationError(_('Amount has to be positive'))
        return amount

    def clean_date(self):
        recurrence_date = self.cleaned_data['date']
        if recurrence_date < date.today():
            raise forms.ValidationError(_("Date can't be in the past"))
        return recurrence_date

    def clean(self):
        if self.cleaned_data['transaction_type'] == Transaction.TRANSFER:
            src_type = dst_type = Account.PERSONAL
        elif self.cleaned_data['transaction_type'] == Transaction.WITHDRAW:
            src_type = Account.PERSONAL
            dst_type = Account.EXPENSE
        else:
            src_type = Account.REVENUE
            dst_type = Account.PERSONAL
        src, _ = Account.objects.get_or_create(name=self.cleaned_data['src'],
                                               account_type=src_type)
        self.cleaned_data['src'] = src
        dst, _ = Account.objects.get_or_create(name=self.cleaned_data['dst'],
                                               account_type=dst_type)
        self.cleaned_data['dst'] = dst


class ReconcilationForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['title', 'current_balance', 'notes']

    current_balance = forms.DecimalField(max_digits=10, decimal_places=2, required=True)

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super(ReconcilationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        transaction = super().save(False)
        transaction.transaction_type = Transaction.SYSTEM
        transaction.save()
        src = Account.objects.get(account_type=Account.SYSTEM).pk
        dst = Account.objects.get(pk=self.account)
        balance = self.cleaned_data['current_balance']
        amount = balance - dst.balance
        Split.objects.create(transaction=transaction, amount=-amount,
                             account_id=src, opposing_account=dst, title=transaction.title)
        Split.objects.create(transaction=transaction, amount=amount,
                             account=dst, opposing_account_id=src, title=transaction.title)
        return transaction

    def clean(self):
        super().clean()
        if self.cleaned_data['current_balance'] == Account.objects.get(pk=self.account).balance:
            self.add_error('current_balance', 'You provided the same balance!')


class Grouped(object):
    def __init__(self, queryset, group_by_field,
                 group_label=None, *args, **kwargs):
        """
        ``group_by_field`` is the name of a field on the model to use as
                           an optgroup.
        ``group_label`` is a function to return a label for each optgroup.
        """
        queryset = queryset.order_by(group_by_field)
        super(Grouped, self).__init__(queryset, *args, **kwargs)
        self.group_by_field = group_by_field
        if group_label is None:
            self.group_label = lambda group: group
        else:
            self.group_label = group_label

    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return GroupedModelChoiceIterator(self)


class GroupedModelChoiceIterator(ModelChoiceIterator):
    def __iter__(self):
        if self.field.empty_label is not None:
            yield ("", self.field.empty_label)
        queryset = self.queryset.all()
        if not queryset._prefetch_related_lookups:

silverstrike/views/charts.py
from datetime import date

from dateutil.relativedelta import relativedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from silverstrike.lib import last_day_of_month


class ChartView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'silverstrike/charts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'charts'
        context['today'] = date.today()
        context['minus_3_months'] = date.today() - relativedelta(months=3)
        context['minus_6_months'] = date.today() - relativedelta(months=6)
        context['minus_12_months'] = date.today() - relativedelta(years=1)

        context['first_day_of_month'] = date.today().replace(day=1)
        context['last_day_of_month'] = last_day_of_month(date.today())
        return context

silverstrike/templates/silverstrike/account_confirm_delete.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Delete '{{ object.name }}' account
</h1>
{% endblock %}

{% block content %}
<div class="col-md-offset-3 col-md-6">
<div class="box">
  <form method="post" class="form-horizontal">
    <div class="box-body">
      {% csrf_token %}
        <p>Are you sure you want to delete the account along with {{ account.transaction_num }} transactions?</p>
        <div class="text-center">
        <a href="{{ account.get_absolute_url }}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
      </div>
    </div>
  </form>

</div>
</div>
{% endblock %}

silverstrike/templates/silverstrike/account_form.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Accounts
  {% if object %}
  <small>Update {{ object.name }}</small>
  {% else %}
  <small>Create new account</small>
  {% endif %}
</h1>
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="#">Accounts</a></li>
  {% if object %}
  <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="active">{% trans 'Update' %}</li>
  {% else %}
  <li class="active">{% trans 'New' %}</li>
  {% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">{% trans 'Account Details' %}</h3>
  </div>
  <form method="post" class="form-horizontal">
    <div class="box-body">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {% if field|widget_type != "checkboxinput" %}
        <label class="control-label col-sm-2" for="{{ field.id_for_label }}">{{ field.label }}</label>
        <div class="col-sm-8">
          {% render_field field placeholder=field.label class="form-control" %}
        </div>
        {% else %}
        <div class="col-sm-offset-2 col-sm-8 ">
          <div class="checkbox">
            <label>
              {{ field }}
              {{ field.label }}
            </label>
          </div>
        </div>
        {% endif %}
        {% for error in  field.errors %}
        <span class="help-block">{{ errror }}<span>
            {% endfor %}
      </div>
      {% endfor %}
    </div>
    <div class="box-footer">
      <div class="col-sm-offset-2">
        <a href="{{ account.get_absolute_url }}" class="btn btn-default">{% trans 'Cancel' %}</a>
        <button type="submit" class="btn btn-primary">{% if object %}{% trans 'Update' %}{% else %}{% trans 'Create' %}{% endif %}</button>
      </div>
    </div>
  </form>

</div>
{% endblock %}

silverstrike/templates/silverstrike/accounts.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content_header %}
<h1>Accounts
  <small>Only showing accounts that have transactions</small>
</h1>
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Accounts</li>
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">{% trans 'Accounts' %}</h3>
  </div>
  <div class="box-body no-padding">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Balance</th>
        <th>Active</th>
      </tr>
      {% for account in accounts %}
      <tr>
        <td><a href="{% url 'account_view' account.id %}">{{ account.name }}</a></td>
        <td>{{ account.balance }}</td>
        <td>{% if account.active %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-close"></i>{% endif %}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="box-footer">
    <a class="btn btn-primary pull-right" href="{% url 'account_new' %}">{% trans 'New' %}</a>
  </div>
</div>
{% endblock %}

silverstrike/templates/silverstrike/base.html
{% load staticfiles %}
{% load i18n %}
{% load account %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" sizes="192x192" href="{% static 'silverstrike/img/icon-192.png' %}">
    <link rel="icon" sizes="128x128" href="{% static 'silverstrike/img/icon-128.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'silverstrike/img/favicon.png' %}" />
    <link rel="manifest" href="{% url 'manifest' %}">
    {% block stylesheets %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'silverstrike/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/skin-blue-light.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


    <title>SilverStrike</title>
  </head>
  <body class="hold-transition skin-blue-light sidebar-mini">
    <div class="wrapper">

      <header class="main-header">
        <a href="/" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>AgS</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Silver</b>strike</span>
        </a>
        <nav class="navbar navbar-static-top">
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>

          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">New</a>
              <ul class="dropdown-menu">
                <li class="header">
                  <a href="{% url 'withdraw_new' %}">{% trans 'New Withdrawl' %}</a>
                </li>
                <li>
                  <a href="{% url 'deposit_new' %}">{% trans 'New Deposit' %}</a>
                </li>
                <li>
                  <a href="{% url 'transfer_new' %}">{% trans 'New Transfer' %}</a>
                </li>
                <li>
                  <a href="{% url 'split_create' %}">{% trans 'New Split Transaction' %}</a>
                </li>
              </ul>
              </li>
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <span class="hidden-xs">{% user_display user %}
</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="user-header" id="navbar-user">
                    <p>
                    {% if request.user.first_name %}
                    {{ request.user.first_name }} {{ request.user.last_name }}
                    {% else %}
                    {% user_display user %}
                    {% endif %}
                    </p>
                  </li>
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{% url 'account_email' %}" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'account_logout' %}" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <aside class="main-sidebar">
        <section class="sidebar">
          <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li {% if menu == "home" %}class="active"{% endif %}>
              <a href="/">
                <i class="fa fa-home"></i> <span>Home</span>
              </a>
            </li>
            <li{% if menu == "accounts" %} class="active"{% endif %}>
                <a href="{% url 'accounts' %}">
                  <i class="fa fa-book fa-fw"></i>
                  <span>{% trans 'Accounts' %}</span>
                </a>
            </li>
            <li class="{% if menu == "transactions" %}active{% endif %}">
              <a href="{% url 'transactions' %}">
                <i class="fa fa-exchange fa-fw"></i>
                <span>Transactions</span>
              </a>
            </li>
            <li{% if menu == "recurrences" %} class="active"{% endif %}><a href="{% url 'recurrences' %}"><i class="fa fa-repeat"></i>
            <span>Recurrences</span></a></li>
            <li{% if menu == "categories" %} class="active"{% endif%}>
              <a href="{% url 'categories' %}">
              <i class="fa fa-tags" aria-hidden="true"></i>
              <span>{% trans 'Categories' %}</span>
              </a>
            </li>
            <li{% if menu == "charts" %} class="active"{% endif %}>
              <a href="{% url 'charts' %}">
              <i class="fa fa-line-chart" aria-hidden="true"></i>
              <span>{% trans 'Charts' %}</span>
              </a>
            <li class="treeview{% if menu == "settings" %} active{% endif %}">
              <a href="#">
                <i class="fa fa-wrench fa-fw"></i>
                <span>Settings</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li>
                  <a href="{% url 'import' %}"><i class="fa fa-download fa-fw"></i>{% trans 'Import' %}</a>
                </li>
                <li>
                  <a href="{% url 'export' %}"><i class="fa fa-upload fa-fw"></i>{% trans 'Export' %}</a>
                </li>
              </ul>
            </li>
          </ul>
        </section>
      </aside>
      <div class="content-wrapper">
        <section class="content-header">
          {% block content_header %}
          {% endblock %}
        </section>
        <section class="content">
          {% block content %}
          {% endblock %}
        </section>
      </div>
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 0.1
        </div>
        <strong><a href="https://github.com/AgStrike/SilverStrike">SilverStrike</a></strong>
      </footer>
    </div>
    <script src="{% static 'silverstrike/js/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/js/adminlte.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
    <script>
      $(document).ready(function () {
        $('.sidebar-menu').tree()
      })
    </script>
  </body>
</html>

silverstrike/templates/silverstrike/reconcile.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>{{ account|title }}
  <small>
  Reconcile
  </small>
</h1>
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="{% url 'accounts' %}">Accounts</a></li>
  <li><a href="{{ account.get_absolute_url }}">{{ account }}</a></li>
  <li class="active">Reconcile</li>
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
  <h3 class="box-title">{% trans 'Current Balance:' %} {{ account.balance }}</h3>
</div>
<div class="box-body">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}
          </label>
          <div class="col-sm-8">
          {{ field|add_class:"form-control" }}
          {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary col-md-offset-2">{% if object %}{% trans 'Update' %}{% else %}{% trans 'Create' %}{% endif %}</button>
    </form>
</div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap3-typeahead.min.js' %}"></script>

<script>
$(function() {
  $('#id_date').datepicker({
  autoclose: true,
  format: 'yyyy-mm-dd',
  endDate: '0d',
  orientation: 'bottom',

  })
  if ($('input#id_source_account').length > 0) {
      $.getJSON('{% url 'api_accounts' 'REVENUE' %}').done(function (data) {
          $('#id_source_account').typeahead({source: data});
      });
  }
  if ($('input#id_destination_account').length > 0) {
      $.getJSON('{% url 'api_accounts' 'EXPENSE' %}').done(function (data) {
          $('#id_destination_account').typeahead({source: data});
      });
  }
  $('#id_date').attr('autocomplete', 'off');
})
</script>
{% endblock %}